MODEL_NAME_LLM: gpt-3.5-turbo-instruct
ALIAS: default
URI: http://localhost:19530
# MILVUS_TOKEN: root:Milvus
LOGGING_LEVEL: INFO
N_FOR_PROMPT: 150
TRESHOLD_DIRECT_ACCEPT: 0.95
TRESHOLD_CANDIDATE_ACCEPT: 0.95
DEVICE: mps

PORT: 8031

